import Head from 'next/head'
import Landing from './landing'

export default function Home() {
  return (
    <div className='container'>
      <Head>
      <title>Edusopher | Your One Stop Place For All Your Study Related Querry</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Landing/>
      
    </div>
  )
}
